name: Label New Issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Add "To Do" label to new issues
        uses: andymckay/labeler@master
        with:
          add-labels: "To Do"
